app/routes.php
<?php

use Darsain\Console\Console;

// Rotas publicas
Route::get('login.aspx', function () {
    return Redirect::to('auth/login');
});
Route::controller('auth', 'AuthController');

// Rotas autorizadas somente a usuários logados
Route::group(array(
    'before' => 'autenticado'
        ), function () {

    Route::controller('home', 'HomeController');
    Route::get('/', function () {
        if (Auth::user()->id_nivel < 10) {
            if (Auth::user()->fl_primeira_vez) {
                return Redirect::to('publico/usuario/meusdados');
            } else {
                return Redirect::to('home/bemvindocliente');
            }
        } else {
            return Redirect::to('home/bemvindo');
        }
    });

    Route::group(array(
        'prefix' => 'publico'
            ), function () {
        Route::controller('anexo', 'AnexoClienteController');
        Route::controller('documento', 'DocumentoClienteController');
        Route::controller('usuario', 'UsuarioClienteController');
        Route::controller('os', 'OrdemServicoClienteController');
        Route::controller('caixa', 'CaixaClienteController');
        Route::controller('centrodecusto', 'CentrodecustoClienteController');
        Route::controller('departamento', 'DepartamentoClienteController');
        Route::controller('setor', 'SetorClienteController');
        Route::controller('reserva', 'ReservaClienteController');
        Route::controller('propriedade', 'PropriedadeClienteController');
        Route::controller('remessa', 'RemessaClienteController');
    });

    // Rotas autorizadas somente aos usuários nivel > 10 (internos)
    Route::group(array(
        'before' => 'backoffice'
            ), function () {

        View::composer('padrao/combos/clientes', 'PreencheComboComposer');
        View::composer('stilearn-metro', 'ProtocoloOsComposer');

        Route::controller('aviso', 'AvisoController');
        Route::controller('anexo', 'AnexoController');
        Route::controller('caixa', 'CaixaController');
        Route::controller('checkin', 'CheckinController');
        Route::controller('checkinok', 'CheckinController');
        Route::controller('checkinxx', 'CheckinController');
        Route::controller('checkout', 'CheckoutController');
        Route::controller('cliente', 'ClienteController');
        Route::controller('consultaboletos', 'ConsultaBoletosController');
        Route::controller('configetiqueta', 'ConfigEtiquetaController');
        Route::controller('documento', 'DocumentoController');
        Route::controller('diavencimento', 'DiaVencimentoController');
        Route::controller('digitacao', 'DigitacaoController');
        Route::controller('envelopecobr', 'EnvelopeCobrController');
        Route::controller('etiqueta', 'EtiquetaController');
        Route::controller('endereco', 'EnderecoController');
        Route::controller('expurgo', 'ExpurgoController');
        Route::controller('faturamento', 'FaturamentoController');
        Route::controller('galpao', 'GalpaoController');
        Route::controller('gerencial', 'GerencialController');
        Route::controller('importador', 'ImportadorController');
        Route::controller('modelo', 'ModeloController');
        Route::controller('nivel', 'NivelController');
        Route::controller('notacarioca', 'NotacariocaController');
        Route::controller('ordemservico', 'OrdemServicoController');
        Route::controller('osok', 'OrdemServicoController');
        Route::controller('periodofat', 'PeriodoFaturamentoController');
        Route::controller('sicoobremessa', 'SicoobRemessaController');
        Route::controller('sicoobretorno', 'SicoobRetornoController');
        Route::controller('loterps', 'LoteRpsController');
        Route::controller('tipodocumento', 'TipoDocumentoController');
        Route::controller('tipoemail', 'TipoEmailController');
        Route::controller('tipoproduto', 'TipoProdutoController');
        Route::controller('tipotelefone', 'TipoTelefoneController');
        Route::controller('reserva', 'ReservaController');
        Route::controller('transbordo', 'TransbordoController');
        Route::controller('retorno', 'RetornoController');
        Route::controller('remessa', 'RemessaController');
        Route::controller('usuario', 'UsuarioController');
    });
});

// Binds para interfaces definidas no sistema
App::bind('Memodoc\Repositorios\RepositorioOsInterface', 'Memodoc\Repositorios\RepositorioOsEloquent');

// Validadores
if (\Auth::user()) {
    if (\Auth::user()->id_nivel < 10) {
        $propriedade = \Propriedade::where('id_cliente', '=', \Auth::user()->id_cliente)->first();
        View::share('propriedade', $propriedade);
    }
}

app/models/Boleto.php
<?php
use \Carbon;

class Boleto extends Modelo {

    protected $table = 'boleto';
    protected $primaryKey = 'id_boleto';
    protected $fillable = array();

    public function cliente(){
            return $this->belongsTo('Cliente', 'id_cliente', 'id_cliente');
    }

    public function getLinhaDigitavelAttribute(){
        return '&nbsp;';
    }

    public function getDtVencimentoAttribute(){
        return '&nbsp;';
    }
    public function getBeneficiarioNomeAttribute(){
        return '&nbsp;';
    }
    public function getBeneficiarioCodigoAttribute(){
        return '&nbsp;';
    }
    public function getDtDocumentoAttribute(){
        return '&nbsp;';
    }
    public function getNumDocumentoAttribute(){
        return '&nbsp;';
    }
    public function getEspecieAttribute(){
        return '&nbsp;';
    }
    public function getAceiteAttribute(){
        return '&nbsp;';
    }
    public function getDtProcessamentoAttribute(){
        return '&nbsp;';
    }
    public function getNossoNumeroAttribute(){
        return '&nbsp;';
    }
    public function getQuantidadeAttribute(){
        return '&nbsp;';
    }    
    public function getValorAttribute(){
        return '&nbsp;';
    }    
    public function getValorDocumentoAttribute(){
        return '&nbsp;';
    }    
    public function getCarteiraAttribute(){
        return '&nbsp;';
    }    
    public function getInstrucoesAttribute(){
        return '&nbsp;';
    }    
    public function getDescontoAttribute(){
        return '&nbsp;';
    }    
    public function getOutrasDeducoesAttribute(){
        return '&nbsp;';
    }    
    public function getMoraMultaAttribute(){
        return '&nbsp;';
    }    
    public function getPagadorAttribute(){
        return '&nbsp;';
    }    
    public function getOutrosAcrescimosAttribute(){
        return '&nbsp;';
    }    
    public function getValorCobradoAttribute(){
        return '&nbsp;';
    }    
}

app/models/SicoobRemessa.php
<?php
use Carbon;
/**
 * @property int $id_os_chave
 * @property int $id_caixa
 * @property int $id_cliente
 * @property int $fl_primeira_entrada
 */
class SicoobRemessa extends Eloquent {

    protected $table = 'sicoob_remessa';
    protected $primaryKey = 'id_sicoob_remessa';
    protected $guarded = array();
    public static $rules = array();


    public function raiz(){

        $caminho = storage_path().'/sicoob/remessa/';
        if(!is_dir($caminho)){
            mkdir($caminho, 0775, true);
        }
        return $caminho;
    }

    public function caminho(){
        return $this->raiz();
    }
    

    public function caminho_com_arquivo(){
        return $this->raiz().$this->id_sicoob_remessa;
    }    

    public function valores_em_array(){
        $ret = [];
        
        $ret['data_carga'] = Carbon::createFromFormat('Y-m-d',$this->data_carga)->format('dmy');
        $ret['id_sicoob_remessa'] = $this->id_sicoob_remessa;
        
        return $ret;
    }
}

app/controllers/SicoobRemessaController.php
<?php

use Carbon\Carbon;
use Memodoc\Repositorios;

class SicoobRemessaController extends BaseController {
    public function getIndex() {
        $lotes_rps = \LoteRps::orderBy('id_lote_rps', 'desc')->lists('id_lote_rps', 'id_lote_rps');
        $remessas = \SicoobRemessa::orderBy('id_sicoob_remessa', 'desc')->get();
        return View::make('sicoob_remessa/index')
                        ->with('lotes_rps', $lotes_rps)
                        ->with('remessas', $remessas)
                        ;
    }

    public function postIndex() {
        return Redirect::to('/sicoobremessa');
    }

    public function getGerarlote($id_lote_rps ){
        set_time_limit(0);

        $lote = \LoteRps::find($id_lote_rps);
        $remessa = new \SicoobRemessa;
        $remessa->data_carga = Carbon::now('America/Sao_Paulo')->format('Y-m-d');
        $remessa->id_lote_rps = $id_lote_rps;
        $remessa->save();

        $arquivo = new \Memodoc\Utilitarios\ArquivoSicoobRemessa($remessa);
        
        $caminho = $arquivo->gerar();
        $headers = array(
            'Content-type' => "application/txt",
            'Content-Transfer-Encoding' => 'binary',
            'Content-Description' => 'File Transfer',
            'Expires' => 0,
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Pragma' => 'public'
        );
        return Response::download($caminho, 'remessa_'.$remessa->id_sicoob_remessa.'.txt', $headers);
    }

    public function getRegerar($id_sicoob_remessa){
        set_time_limit(0);
        
        $remessa = \SicoobRemessa::find($id_sicoob_remessa);

        $arquivo = new \Memodoc\Utilitarios\ArquivoSicoobRemessa($remessa);
        
        $caminho = $arquivo->gerar();

        $headers = array(
            'Content-type' => "text/plain",
            'Expires' => 0,
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Pragma' => 'public'
        );
        return Response::download($caminho, 'remessa_'.$remessa->id_sicoob_remessa.'.txt', $headers);
        
    }

    public function getDetalhe($id_sicoob_retorno){
        $retorno = \SicoobRetorno::find($id_sicoob_retorno);
        $regs = \RegistroSicoobRetorno::where('id_sicoob_retorno', '=', $id_sicoob_retorno)->orderBy('ordem', 'asc')->get();
        
        return View::make('sicoob_retorno/detalhe')
                    ->with('regs', $regs)
                    ->with('retorno', $retorno)
                    ;        
    }

    public function getProcessar($id_lote_rps){
        $rep = new Repositorios\RepositorioImportadorSicoobRetorno;
        $rep->processa_arquivo($id_sicoob_retorno);
        Session::flash('success', 'Arquivo reprocessado com sucesso!!');
        return Redirect::to('/sicoobretorno');
    }

    public function getBoleto($id_nota_fiscal){
        $boleto = new \Boleto;
        
        return View::make('sicoob_remessa/boleto')
            ->with('boleto', $boleto)
        ;        
    }
}

app/views/sicoob_remessa/boleto.blade.php
<html>
    <head>
        <style>
            table{
                border-collapse:collapse;
            }
            td{
                border: solid 1px #000000;
                font-family: arial;
                font-size:11px;
            }
            tr.def td{
                border: none;
            }
            td.cheia{
                border-top:none;
                border-bottom:none;
            }
            tr.topo td{
                border-bottom: none;
                font-weight: bold;
                padding-bottom: 4px;
            }
            tr.base td{
                border-top: none;
                font-size:12px;
            }
            td.fundo-cinza{
                background-color: #cccccc;
            }
        </style>
    </head>
    <body>
        <table>
        <!-- Define colunas -->
            <tr class="def">
                <td width="200px">&nbsp;</td>
                <td width="80px">&nbsp;</td>
                <td width="80px">&nbsp;</td>
                <td width="80px">&nbsp;</td>
                <td width="80px">&nbsp;</td>
                <td width="150px">&nbsp;</td>
                <td width="250px">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7"><img src="/img/logo.jpg"/></td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="7" class="cheia">&nbsp;</td>
            </tr>

        <!-- Linha A - Banco e linha digitável -->
            <tr class="base">
                <td colspan="2"><img src=""/></td> <!-- Logo -->
                <td style="font-size:22px; font-weight:bold">756-0</td> <!-- Banco -->
                <td colspan="4">{{ $boleto->linha_digitavel }}</td> <!-- Linha digitavel -->
            </tr>
        <!-- Linha B título -->
            <tr class="topo">
                <td colspan="6">Local de pagamento</td> <!-- Local de pagamento -->
                <td class="fundo-cinza">Vencimento</td> <!-- Vencimento -->
            </tr>
        <!-- Linha B conteúdo -->
            <tr class="base">
                <td colspan="6">Pagável em qualquer banco até a data do vencimento</td> <!-- Local de pagamento -->
                <td class="fundo-cinza">{{ $boleto->dt_vencimento }}</td> <!-- Vencimento -->
            </tr>
        <!-- Linha C título -->
            <tr class="topo">
                <td colspan="6">Beneficiário</td>
                <td class="fundo-cinza">Agência/Código Beneficiário</td>
            </tr>
        <!-- Linha C conteúdo -->
            <tr class="base">
                <td colspan="6">{{ $boleto->beneficiario_nome }}</td>
                <td class="fundo-cinza">{{ $boleto->beneficiario_codigo }}</td>
            </tr>
        <!-- Linha D título -->
            <tr class="topo">
                <td >Data do documento</td>
                <td colspan="2">N. documento</td>
                <td >Espécie</td>
                <td >Aceite</td>
                <td >Dt processamento</td>
                <td >Nosso número</td>
            </tr>
        <!-- Linha D conteudo -->
            <tr class="base">
                <td >{{ $boleto->dt_documento }}</td>
                <td colspan="2">{{ $boleto->num_documento }}</td>
                <td >{{ $boleto->especie }}</td>
                <td >{{ $boleto->aceite }}</td>
                <td >{{ $boleto->dt_processamento }}</td>
                <td >{{ $boleto->nosso_numero }}</td>
            </tr>
        <!-- Linha E título -->
            <tr class="topo">
                <td class="fundo-cinza">Uso do banco</td>
                <td>Carteira</td>
                <td >Espécie</td>
                <td colspan="2" >Quantidade</td>
                <td >Valor</td>
                <td >Valor Documento</td>
            </tr>
        <!-- Linha E título -->
            <tr class="base">
                <td class="fundo-cinza">&nbsp;</td>
                <td>{{ $boleto->carteira }}</td>
                <td>{{ $boleto->especie }}</td>
                <td colspan="2" >{{ $boleto->quantidade }}</td>
                <td >{{ $boleto->valor }}</td>
                <td >{{ $boleto->valor_documento }}</td>
            </tr>
        <!-- Linha F título -->
            <tr class="topo">
                <td colspan="6">Instruções</td>
                <td>(-)Desconto/abatimento</td>
            </tr>
        <!-- Linha F conteudo -->
            <tr class="base">
                <td colspan="6" rowspan="5">{{ $boleto->instrucoes }}</td>
                <td>{{ $boleto->desconto }}</td>
            </tr>
        <!-- Linha H título -->
            <tr class="topo">
                <td>(-)Outras deduções</td>
            </tr>
        <!-- Linha H conteudo -->
            <tr class="base">
                <td>{{ $boleto->outras_deducoes }}</td>
            </tr>
        <!-- Linha I título -->
            <tr class="topo">
                <td>(+)Mora/multa</td>
            </tr>
        <!-- Linha i conteudo -->
            <tr class="base">
                <td>{{ $boleto->mora_multa }}</td>
            </tr>
        <!-- Linha j título -->
            <tr class="topo">
                <td colspan="6">Pagador</td>
                <td>(+)Outros acréscimos</td>
            </tr>
        <!-- Linha j conteudo -->
            <tr class="base">
                <td colspan="6" rowspan="3">{{ $boleto->pagador }}</td>
                <td>{{ $boleto->outros_acrescimos }}</td>
            </tr>
        <!-- Linha H título -->
            <tr class="topo">
                <td>Valor cobrado</td>
            </tr>
        <!-- Linha H conteudo -->
            <tr class="base">
                <td>{{ $boleto->valor_cobrado }}</td>
            </tr>
        </table>
    </body>
</html>

app/views/sicoob_remessa/index.blade.php
@extends('stilearn-metro')

@section('conteudo')

<!-- content header -->
<header class="content-header"><h1>SICOOB - Gerar boletos</h1></div>

    <!-- content breadcrumb -->
    <div class='content-action pull-right'>
    </div>
</header> <!--/ content header -->

<!-- content page -->
<article class="content-page clearfix">

    <!-- main page -->
    <div class="main-page">
        <div class="content-inner">

            @include('padrao.mensagens')

            <div class="widget border-cyan">
                <!-- widget header -->
                <div class="widget-header">
                    <!-- widget icon -->
                    <div class="widget-icon"><i class="aweso-search"></i></div>
                    <!-- widget title -->
                    <h4 class="widget-title">Gerar uma nova remessa</h4>
                </div><!-- /widget header -->

                <!-- widget content -->
                <div class="widget-content">
                    {{ Form::open(array('class'=> 'form-horizontal', 'files'=> true, 'url'=> '/sicoobretorno/novaconsulta')) }}
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label class="control-label">Lote de notas</label>
                                <div class="controls">
                                    {{Form::select('id_lote_rps', $lotes_rps, null, array('id'=>'id_lote_rps','data-fx'=>'select2', 'required', 'class' => 'input-block-level'))}}
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                        </div>
                    </div>
                    <div class="form-actions bg-silver">
                        <button type="submit" class="btn bg-orange">Enviar</button>
                    </div>

                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</article> <!-- /content page -->
<style>
    .c{
        width:200px;
        text-align:center;
    }
</style>
@stop